# Generated by Django 4.1 on 2023-05-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(default="", max_length=256)),
                ("gender", models.IntegerField(default=0)),
                ("intro", models.CharField(default="", max_length=256)),
                (
                    "organization",
                    models.CharField(default="", max_length=50, verbose_name="所属组织"),
                ),
                ("destination", models.CharField(default="", max_length=256)),
                ("job", models.CharField(default="", max_length=256)),
                ("followers", models.IntegerField(default=0, verbose_name="粉丝数")),
                ("like", models.IntegerField(default=0, verbose_name="点赞数")),
                ("tags", models.CharField(default="", max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="StudySpaces",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("space_name", models.CharField(max_length=50)),
                ("space_introduction", models.CharField(max_length=200)),
                ("space_index", models.CharField(max_length=1000)),
                ("space_picture", models.BinaryField()),
                ("create_time", models.DateTimeField()),
                (
                    "creator_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceResources",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=100)),
                ("file", models.BinaryField()),
                ("create_time", models.DateTimeField()),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.studyspaces",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceQuestions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=1000)),
                ("create_time", models.DateTimeField()),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.studyspaces",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceNotices",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=500)),
                ("create_time", models.DateTimeField()),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.studyspaces",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceGroups",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=50)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="SpaceGroups_Users", to="app01.user"
                    ),
                ),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.studyspaces",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceExercises",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=10)),
                ("difficulty", models.CharField(max_length=10)),
                ("answer", models.CharField(max_length=100)),
                ("create_time", models.DateTimeField()),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.studyspaces",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpaceComments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_type", models.IntegerField()),
                ("content", models.CharField(max_length=500)),
                ("create_time", models.DateTimeField()),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.studyspaces",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice_type", models.CharField(max_length=256)),
                ("notice_id", models.IntegerField(verbose_name="通知内容（评论等）的ID")),
                ("notice_title", models.CharField(max_length=256)),
                ("create_time", models.DateField(auto_now=True)),
                (
                    "hosts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texts", models.TextField()),
                ("user2", models.IntegerField()),
                ("texts_time", models.DateField(auto_now=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like_type", models.CharField(max_length=256)),
                ("liked_id", models.IntegerField()),
                (
                    "hosts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed_type", models.CharField(max_length=50)),
                ("followed_id", models.IntegerField(verbose_name="关注的人/学习空间id")),
                ("create_time", models.DateField(auto_now=True)),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.user",
                        verbose_name="关注者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collect_type", models.CharField(max_length=256)),
                ("collect_id", models.IntegerField(verbose_name="通知内容（评论等）的ID")),
                ("collect_title", models.CharField(max_length=256)),
                ("create_time", models.DateField(auto_now=True)),
                (
                    "hosts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("create_time", models.DateField(auto_now=True)),
                ("programs", models.CharField(max_length=256)),
                (
                    "hosts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
        ),
    ]
