# Generated by Django 4.1 on 2023-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="s_id",
            field=models.IntegerField(default=0),
        ),
    ]
