# Generated by Django 4.1.7 on 2023-05-11 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='', max_length=50, verbose_name='所属组织'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='spacegroups',
            name='members',
            field=models.ManyToManyField(related_name='Space_Groups_to_Users', to='app01.user'),
        ),
        migrations.AlterModelTable(
            name='spacecomments',
            table='Space_Comments',
        ),
        migrations.AlterModelTable(
            name='spaceexercises',
            table='Space_Exercises',
        ),
        migrations.AlterModelTable(
            name='spacegroups',
            table='Space_Groups',
        ),
        migrations.AlterModelTable(
            name='spacenotices',
            table='Space_Notices',
        ),
        migrations.AlterModelTable(
            name='spacequestions',
            table='Space_Questions',
        ),
        migrations.AlterModelTable(
            name='spaceresources',
            table='Space_Resources',
        ),
        migrations.AlterModelTable(
            name='studyspaces',
            table='StudySpaces',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_type', models.CharField(max_length=256)),
                ('notice_id', models.IntegerField(verbose_name='通知内容（评论等）的ID')),
                ('notice_title', models.CharField(max_length=256)),
                ('create_time', models.DateField(auto_now=True)),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
            options={
                'db_table': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texts', models.TextField()),
                ('user2', models.IntegerField()),
                ('texts_time', models.DateField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
            options={
                'db_table': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like_type', models.CharField(max_length=256)),
                ('liked_id', models.IntegerField()),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followed_type', models.CharField(max_length=50)),
                ('followed_id', models.IntegerField(verbose_name='关注的人/学习空间id')),
                ('create_time', models.DateField(auto_now=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='关注者')),
            ],
            options={
                'db_table': 'Follows',
            },
        ),
        migrations.CreateModel(
            name='Collects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collect_type', models.CharField(max_length=256)),
                ('collect_id', models.IntegerField(verbose_name='通知内容（评论等）的ID')),
                ('collect_title', models.CharField(max_length=256)),
                ('create_time', models.DateField(auto_now=True)),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
            options={
                'db_table': 'Collects',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('create_time', models.DateField(auto_now=True)),
                ('programs', models.CharField(max_length=256)),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
