# Generated by Django 4.1 on 2023-05-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ConfirmString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=256)),
                ("c_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "确认码",
                "verbose_name_plural": "确认码",
                "db_table": "tb_confirmCode",
                "ordering": ["-c_time"],
            },
        ),
    ]
