# Generated by Django 4.1 on 2023-05-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="t_id",
            field=models.IntegerField(default=0),
        ),
    ]
